[build]
  publish = "public"

[[redirects]]
  from = "/v1/*"
  to = "https://models.inference.ai.azure.com/:splat"
  status = 200
  force = true
  headers = {Authorization = ":auth", Content-Type = "application/json"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200